using UnityEngine;
using UnityEngine.UI;
using UnityEngine.Rendering;
using UnityEngine.EventSystems;

public class InventorySlotUI : MonoBehaviour,
    IPointerEnterHandler,
    IPointerExitHandler,
    IBeginDragHandler,
    IDragHandler,
    IEndDragHandler,
    IPointerClickHandler
{
    public Text label;
    public Image icon;
    // Optional RawImage that will display the RenderTexture generated by
    // InventoryPreviewRenderer. If left null, the existing sprite-based
    // icon logic is used as a fallback.
    public RawImage previewRaw;

    public Sprite emptyIcon;

    public enum SlotType
    {
        Backpack,
        RightHand,
        Accessory,
        WandInternal
    }

    [Header("Slot Type")]
    public SlotType slotType = SlotType.Backpack;

    [HideInInspector] public int slotIndex = -1;
    [HideInInspector] public PlayerInventory inventory;
    [HideInInspector] public WandItem wandOwner;
    [HideInInspector] public int wandSlotIndex = -1;

    static InventorySlotUI hoveredSlot;
    static InventorySlotUI draggingSlot;

    public static InventorySlotUI HoveredSlot => hoveredSlot;

    private PlayerUI playerUI;

    void Awake()
    {
        playerUI = GetComponentInParent<PlayerUI>();
    }
    public void SetItem(GameObject item, int index = -1, PlayerInventory inv = null)
    {
        slotIndex = index;
        inventory = inv;

        if (label != null)
            label.text = item != null ? ItemTooltipDataUtility.GetDisplayName(item) : string.Empty;

        bool usedPreview = false;

        if (previewRaw != null && item != null)
        {
            var previewProvider = item.GetComponent<IInventoryPreviewProvider>();

            if (previewProvider != null && previewProvider.PreviewPrefab != null && InventoryPreviewRenderer.Instance != null)
            {
                // Pass the whole provider to get Rotation/Scale
                RenderTexture rt = InventoryPreviewRenderer.Instance.RenderPreview(previewProvider);
                previewRaw.texture = rt;
                previewRaw.enabled = true;

                if (icon != null) icon.enabled = false; // Hide the 2D icon
                usedPreview = true; // IMPORTANT: Prevents fallback below
            }
        }

        // Fallback to Sprite Icon
        if (!usedPreview && icon != null)
        {
            Sprite s = emptyIcon;
            if (item != null)
            {
                Sprite resolved = ItemTooltipDataUtility.GetInventoryIcon(item);
                if (resolved != null) s = resolved;
            }

            icon.sprite = s;
            icon.enabled = true;
            if (previewRaw != null) previewRaw.enabled = false;
        }
    }
    public void OnPointerEnter(PointerEventData eventData)
    {
        hoveredSlot = this;
    }

    public void OnPointerExit(PointerEventData eventData)
    {
        if (hoveredSlot == this)
            hoveredSlot = null;
    }

    public void OnBeginDrag(PointerEventData eventData)
    {
        if (inventory == null || playerUI == null)
            return;

        if (!playerUI.IsBackpackOpen)
            return;

        GameObject item = null;

        switch (slotType)
        {
            case SlotType.Backpack:
                if (slotIndex >= 0 && slotIndex < inventory.backpack.Length)
                    item = inventory.backpack[slotIndex];
                break;

            case SlotType.RightHand:
                item = inventory.rightHandItem;
                break;

            case SlotType.Accessory:
                if (slotIndex >= 0 && slotIndex < inventory.accessories.Length)
                    item = inventory.accessories[slotIndex];
                break;

            case SlotType.WandInternal:
                if (wandOwner != null && wandSlotIndex >= 0)
                    item = wandOwner.GetSlotItem(wandSlotIndex);
                break;
        }

        if (item == null)
            return;

        draggingSlot = this;

        Sprite dragSprite = icon != null ? icon.sprite : null;
        playerUI.StartDrag(item, dragSprite, this, slotIndex);
    }

    public void OnDrag(PointerEventData eventData)
    {
        if (draggingSlot != this || playerUI == null)
            return;

        if (!playerUI.IsBackpackOpen)
            return;

        playerUI.UpdateDrag(eventData.position);
    }

    public void OnEndDrag(PointerEventData eventData)
    {
        if (draggingSlot != this || playerUI == null)
        {
            draggingSlot = null;
            return;
        }

        draggingSlot = null;

        if (!playerUI.IsBackpackOpen)
        {
            playerUI.EndDrag();
            return;
        }

        if (hoveredSlot != null)
            playerUI.HandleDrop(hoveredSlot);
        else
            playerUI.EndDrag();
    }

    public void OnPointerClick(PointerEventData eventData)
    {
        if (playerUI == null)
            return;

        playerUI.NotifySlotClicked(this);
    }
}