using UnityEngine;
using UnityEngine.UI;
using UnityEngine.Rendering;
using UnityEngine.EventSystems;

public class InventorySlotUI : MonoBehaviour,
    IPointerEnterHandler,
    IPointerExitHandler,
    IBeginDragHandler,
    IDragHandler,
    IEndDragHandler,
    IPointerClickHandler
{
    public Text label;
    // RawImage that displays the RenderTexture generated by
    // InventoryPreviewRenderer. This replaces the old sprite-based icon system.
    public RawImage previewRaw;
    public enum SlotType
    {
        Backpack,
        RightHand,
        Accessory,
        WandInternal
    }

    [Header("Slot Type")]
    public SlotType slotType = SlotType.Backpack;

    [HideInInspector] public int slotIndex = -1;
    [HideInInspector] public PlayerInventory inventory;
    [HideInInspector] public WandItem wandOwner;
    [HideInInspector] public int wandSlotIndex = -1;

    static InventorySlotUI hoveredSlot;
    static InventorySlotUI draggingSlot;

    public static InventorySlotUI HoveredSlot => hoveredSlot;

    private PlayerUI playerUI;

    void Awake()
    {
        playerUI = GetComponentInParent<PlayerUI>();
    }
    private bool isSelected;
    private Vector3 desiredScale = Vector3.one;
    private float scaleLerpSpeed = 8f;
    [Header("Preview")]
    public Texture placeholderTexture;

    void Update()
    {
        // Determine target scale based on hover/selection and interpolate
        if (previewRaw != null)
        {
            float target = (isSelected || hoveredSlot == this) ? 1.2f : 1.0f;
            Vector3 cur = previewRaw.rectTransform.localScale;
            Vector3 tgt = Vector3.one * target;
            previewRaw.rectTransform.localScale = Vector3.Lerp(cur, tgt, Time.deltaTime * scaleLerpSpeed);
        }
    }
    public void SetItem(GameObject item, int index = -1, PlayerInventory inv = null)
    {
        slotIndex = index;
        inventory = inv;

        if (label != null)
            label.text = item != null ? ItemTooltipDataUtility.GetDisplayName(item) : string.Empty;

        // For wand-internal slots, keep the label hidden until the overlay animation finishes
        if (slotType == SlotType.WandInternal && label != null)
            label.gameObject.SetActive(false);

        // Ensure previewRaw exists and is enabled so raycasts always work.

        // Ensure previewRaw exists. Default to placeholder if available, otherwise hide the preview.
        if (previewRaw != null)
        {
            if (placeholderTexture != null)
            {
                previewRaw.texture = placeholderTexture;
                previewRaw.enabled = true;
            }
            else
            {
                previewRaw.texture = null;
                previewRaw.enabled = false;
            }
            desiredScale = Vector3.one;
        }

        if (previewRaw != null && item != null)
        {
            var previewProvider = item.GetComponent<IInventoryPreviewProvider>();
            if (previewProvider != null && previewProvider.PreviewPrefab != null && InventoryPreviewRenderer.Instance != null)
            {
                RenderTexture rt = InventoryPreviewRenderer.Instance.RenderPreview(previewProvider);
                if (rt != null)
                {
                    previewRaw.texture = rt;
                    previewRaw.enabled = true;
                }
            }
        }

        // If this is a wand-internal slot, only trigger overlay animation for ScrollItems.
        if (slotType == SlotType.WandInternal)
        {
            var overlayComp = GetComponentInChildren<WandSlotOverlay>(true);
            if (overlayComp != null)
            {
                bool isScroll = (item != null && item.GetComponent<ScrollItem>() != null);
                if (isScroll)
                {
                    // Immediately show the final frame and mark as permanent so population
                    // does not replay the entry animation for existing items.
                    overlayComp.SetFinalFrameAndPermanent();
                }
                else
                {
                    overlayComp.ForceDisable();
                }
            }
        }

    }
    public void OnPointerEnter(PointerEventData eventData)
    {
        hoveredSlot = this;
    }

    public void OnPointerExit(PointerEventData eventData)
    {
        if (hoveredSlot == this)
            hoveredSlot = null;
    }

    public void OnBeginDrag(PointerEventData eventData)
    {
        if (inventory == null || playerUI == null)
            return;

        if (!playerUI.IsBackpackOpen)
            return;

        GameObject item = null;

        switch (slotType)
        {
            case SlotType.Backpack:
                if (slotIndex >= 0 && slotIndex < inventory.backpack.Length)
                    item = inventory.backpack[slotIndex];
                break;

            case SlotType.RightHand:
                item = inventory.rightHandItem;
                break;

            case SlotType.Accessory:
                if (slotIndex >= 0 && slotIndex < inventory.accessories.Length)
                    item = inventory.accessories[slotIndex];
                break;

            case SlotType.WandInternal:
                if (wandOwner != null && wandSlotIndex >= 0)
                    item = wandOwner.GetSlotItem(wandSlotIndex);
                break;
        }

        if (item == null)
            return;

        draggingSlot = this;

        RenderTexture dragTex = previewRaw != null ? previewRaw.texture as RenderTexture : null;
        playerUI.StartDrag(item, dragTex, this, slotIndex);
    }

    public void OnDrag(PointerEventData eventData)
    {
        if (draggingSlot != this || playerUI == null)
            return;

        if (!playerUI.IsBackpackOpen)
            return;

        playerUI.UpdateDrag(eventData.position);
    }

    public void OnEndDrag(PointerEventData eventData)
    {
        if (draggingSlot != this || playerUI == null)
        {
            draggingSlot = null;
            return;
        }

        draggingSlot = null;

        if (!playerUI.IsBackpackOpen)
        {
            playerUI.EndDrag();
            return;
        }

        if (hoveredSlot != null)
            playerUI.HandleDrop(hoveredSlot);
        else
            playerUI.EndDrag();
    }

    public void OnPointerClick(PointerEventData eventData)
    {
        if (playerUI == null)
            return;

        // Prevent selecting wand-internal slots (they should not change the description),
        // but still allow hover/drag behavior.
        if (slotType == SlotType.WandInternal)
            return;

        playerUI.NotifySlotClicked(this);
    }

    // Called by PlayerUI when this slot becomes selected/deselected
    public void SetSelected(bool sel)
    {
        isSelected = sel;
        desiredScale = sel ? Vector3.one * 1.2f : Vector3.one;
    }
}